#!/usr/bin/env python3
"""Phase 3 stress quality + M12 envelope-completeness scorer.

This scorer is post-run and read-only.  It consumes the same visibility event
stream the adapters write (``protocol_io.read_events`` for live teams) plus the
workload manifest generated by ``run_scenario.py``.  Workload correctness is
checked against the scenario sandbox; visibility completeness is scored per
agent without flattening backend-native tool names.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from collections import Counter
from pathlib import Path
from typing import Any, Sequence

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"
if SRC_ROOT.exists():
    sys.path.insert(0, str(SRC_ROOT))

from claude_anyteam import protocol_io as pio
from claude_anyteam.messages import VisibilityEvent
from claude_teams import messaging as cs_messaging  # type: ignore[import-untyped]

TERMINAL_KINDS = {"turn_completed", "turn_failed"}

EXPECTED_KINDS_PER_BACKEND: dict[str, list[str]] = {
    "codex_app_server": [
        "turn_started",
        "turn_progress",
        "tool_event",
        "turn_completed",
        "turn_failed",
        "artifact_event",
        "steer_ack",
    ],
    "codex_exec": ["turn_started", "tool_event", "turn_completed", "turn_failed"],
    "gemini_acp": ["turn_started", "tool_event", "turn_completed", "turn_failed", "steer_ack"],
    "gemini_headless": ["turn_started", "turn_completed", "turn_failed"],
    "kimi_headless": ["turn_started", "turn_completed", "turn_failed"],
    "claude_native": ["turn_started", "tool_event", "turn_completed", "turn_failed"],
}

RAW_TOOL_NAME_WHITELIST: dict[str, set[str]] = {
    "codex_app_server": {"commandExecution", "fileChange", "webSearch", "mcpToolCall", "plan", "error"},
    "codex_exec": set(),
    "gemini_acp": {"tool_call", "tool_call_update"},
    "gemini_headless": set(),
    "kimi_headless": set(),
    "claude_native": set(),
}

DEFAULT_SURFACES = ("peer_steer_rejected", "host_tool_stream", "permission_bridge", "peer_dm")
CAPABILITY_MANIFEST_TOOL = "mcp_anyteam_capability_manifest"


class ManifestError(ValueError):
    """Raised when the workload manifest cannot be consumed."""


# ---------------------------------------------------------------------------
# Small utilities


def _warn(message: str) -> None:
    print(f"score_quality: {message}", file=sys.stderr)


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _tail(text: str, *, lines: int = 50, chars: int = 12000) -> str:
    selected = "\n".join(text.splitlines()[-lines:])
    return selected[-chars:]


def _resolve_path(value: str | None, sandbox: Path, *, default: Path) -> Path:
    if not value:
        return default
    rendered = str(value).replace("<sandbox>", str(sandbox))
    path = Path(rendered)
    if not path.is_absolute():
        path = sandbox / path
    return path


def _tool_name(event: VisibilityEvent) -> str | None:
    if event.kind != "tool_event":
        return None
    value = event.payload.get("tool_name") or event.payload.get("raw_backend_type")
    return str(value) if value is not None else None


def _safe_float(value: Any) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _safe_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# Input loading


def _events_dir_for_team(team: str) -> Path:
    return cs_messaging.TEAMS_DIR / team / "events"


def _parse_event_file(path: Path, warnings: list[str]) -> list[VisibilityEvent]:
    events: list[VisibilityEvent] = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            events.append(VisibilityEvent.model_validate_json(line))
        except Exception as exc:
            warnings.append(f"{path.name}:{lineno}: malformed VisibilityEvent skipped: {exc}")
    return events


def _read_events_via_protocol_io(resolved_events_dir: Path, agent: str, team: str | None) -> list[VisibilityEvent]:
    """Read one agent log through ``protocol_io.read_events``.

    Live ``--team`` runs already match the substrate layout.  For archived
    ``--events-dir`` runs, temporarily mount the directory under a throwaway
    ``TEAMS_DIR/<team>/events`` shape so the same reader validates envelopes.
    """

    if team:
        return pio.read_events(team, agent)

    old_root = cs_messaging.TEAMS_DIR
    if resolved_events_dir.name == "events":
        inferred_team = resolved_events_dir.parent.name
        cs_messaging.TEAMS_DIR = resolved_events_dir.parent.parent
        try:
            return pio.read_events(inferred_team, agent)
        finally:
            cs_messaging.TEAMS_DIR = old_root

    with tempfile.TemporaryDirectory(prefix="score-quality-events-") as tmp:
        root = Path(tmp)
        inferred_team = "archived"
        mounted = root / inferred_team / "events"
        mounted.parent.mkdir(parents=True, exist_ok=True)
        try:
            os.symlink(resolved_events_dir, mounted, target_is_directory=True)
        except OSError:
            shutil.copytree(resolved_events_dir, mounted)
        cs_messaging.TEAMS_DIR = root
        try:
            return pio.read_events(inferred_team, agent)
        finally:
            cs_messaging.TEAMS_DIR = old_root


def load_events(*, team: str | None, events_dir: Path | None) -> tuple[dict[str, list[VisibilityEvent]], list[str]]:
    resolved = _events_dir_for_team(team) if team else events_dir
    if resolved is None:  # pragma: no cover - argparse guards this
        raise FileNotFoundError("events source missing")
    if not resolved.exists() or not resolved.is_dir():
        raise FileNotFoundError(f"events dir does not exist: {resolved}")
    paths = sorted(path for path in resolved.glob("*.jsonl") if path.is_file())
    if not paths:
        raise FileNotFoundError(f"events dir contains no *.jsonl files: {resolved}")

    warnings: list[str] = []
    by_agent: dict[str, list[VisibilityEvent]] = {}
    for path in paths:
        agent = path.stem
        try:
            by_agent[agent] = _read_events_via_protocol_io(resolved, agent, team)
            continue
        except Exception as exc:
            # Keep post-run scoring alive while still trying the canonical
            # helper first, per the brief.
            warnings.append(f"{path.name}: read_events failed; tolerant parse used: {exc}")
        by_agent[agent] = _parse_event_file(path, warnings)
    return by_agent, warnings


def load_workload_manifest(path: Path) -> dict[str, Any]:
    if not path.exists() or not path.is_file():
        raise ManifestError(f"workload manifest does not exist: {path}")
    try:
        manifest = _read_json(path)
    except json.JSONDecodeError as exc:
        raise ManifestError(f"workload manifest is not valid JSON: {exc}") from exc
    if not isinstance(manifest, dict):
        raise ManifestError("workload manifest must be a JSON object")
    if manifest.get("schema_version") != 1:
        raise ManifestError("workload manifest schema_version must be 1")
    tasks = manifest.get("tasks")
    if not isinstance(tasks, list):
        raise ManifestError("workload manifest must contain a tasks list")
    return manifest


# ---------------------------------------------------------------------------
# Workload verdicts


def _task_events(task_id: str, all_events: dict[str, list[VisibilityEvent]]) -> list[VisibilityEvent]:
    return [event for events in all_events.values() for event in events if event.task_id == task_id]


def _owner_actual(task_id: str, all_events: dict[str, list[VisibilityEvent]]) -> str | None:
    counts = Counter(event.agent for event in _task_events(task_id, all_events) if event.agent)
    return counts.most_common(1)[0][0] if counts else None


def _task_m7_count(task_id: str, all_events: dict[str, list[VisibilityEvent]]) -> int:
    return sum(1 for event in _task_events(task_id, all_events) if event.kind == "tool_event" and _tool_name(event) == "mcp_anyteam_capability_manifest")


def _run_command(args: Sequence[str], *, cwd: Path, timeout_s: float) -> tuple[str, dict[str, Any], list[str]]:
    started = time.monotonic()
    notes: list[str] = []
    try:
        proc = subprocess.run(
            list(args),
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=timeout_s,
            check=False,
        )
        duration = time.monotonic() - started
        evidence = {
            "command": list(args),
            "cwd": str(cwd),
            "exit_code": proc.returncode,
            "duration_seconds": round(duration, 3),
            "stdout_tail": _tail(proc.stdout),
            "stderr_tail": _tail(proc.stderr),
        }
        return ("pass" if proc.returncode == 0 else "fail"), evidence, notes
    except subprocess.TimeoutExpired as exc:
        duration = time.monotonic() - started
        notes.append("timeout")
        stdout = exc.stdout.decode("utf-8", errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return "fail", {
            "command": list(args),
            "cwd": str(cwd),
            "exit_code": 124,
            "duration_seconds": round(duration, 3),
            "stdout_tail": _tail(stdout),
            "stderr_tail": _tail(stderr),
        }, notes
    except OSError as exc:
        return "fail", {
            "command": list(args),
            "cwd": str(cwd),
            "exit_code": None,
            "duration_seconds": round(time.monotonic() - started, 3),
            "stdout_tail": "",
            "stderr_tail": str(exc),
        }, [f"subprocess_failed:{exc}"]


def _check_pytest_passes(check: dict[str, Any], sandbox: Path, timeout_s: float) -> tuple[str, dict[str, Any], list[str]]:
    cwd = _resolve_path(check.get("cwd"), sandbox, default=sandbox / "repo")
    args = check.get("args") or []
    if not isinstance(args, list):
        args = [str(args)]
    check_timeout = _safe_float(check.get("timeout_s") or check.get("timeout_seconds"))
    return _run_command(
        ["uv", "run", "pytest", *[str(arg) for arg in args]],
        cwd=cwd,
        timeout_s=check_timeout or timeout_s,
    )


def _list_mcp_tools_for_probe() -> tuple[str, ...]:
    """Probe the wrapper MCP tool surface.

    Prefer the dedicated helper if a later branch has added it; otherwise use
    the FastMCP ``list_tools`` API, matching ``tests/test_wrapper_contract.py``.
    """

    from claude_anyteam import wrapper_server

    probe = getattr(wrapper_server, "list_tools_for_probe", None)
    if callable(probe):
        result = probe()
        if isinstance(result, dict):
            tools = result.get("tools") or result.get("tool_names") or result.get("names")
        else:
            tools = result
        return tuple(str(item) for item in tools)
    team = os.environ.get("CLAUDE_ANYTEAM_TEAM") or os.environ.get("CODEX_TEAMMATE_TEAM") or "probe-team"
    name = os.environ.get("CLAUDE_ANYTEAM_NAME") or os.environ.get("CODEX_TEAMMATE_NAME") or "probe-agent"
    mcp = wrapper_server.build_server(["--team", team, "--name", name])
    return tuple(sorted(tool.name for tool in asyncio.run(mcp.list_tools())))


def _wrapper_tool_names() -> tuple[str, ...]:
    return _list_mcp_tools_for_probe()


def _check_mcp_tool_listed(check: dict[str, Any]) -> tuple[str, dict[str, Any], list[str]]:
    args = check.get("args") if isinstance(check.get("args"), dict) else check
    tool_name = str(args.get("tool_name") or "")
    if not tool_name:
        return "unknown_check", {}, ["mcp_tool_listed_missing_tool_name"]
    try:
        tools = _wrapper_tool_names()
    except Exception as exc:
        return "unknown_check", {}, [f"wrapper_probe_failed:{exc}"]
    return ("pass" if tool_name in tools else "fail"), {"tool_name": tool_name, "listed_tools": list(tools)}, []


def _repo_for_check(check: dict[str, Any], sandbox: Path) -> Path:
    args = check.get("args") if isinstance(check.get("args"), dict) else {}
    raw = check.get("cwd") or args.get("cwd") or args.get("repo")
    return _resolve_path(raw, sandbox, default=sandbox / "repo")


def _check_files_modified(check: dict[str, Any], sandbox: Path, timeout_s: float) -> tuple[str, dict[str, Any], list[str]]:
    args = check.get("args") if isinstance(check.get("args"), dict) else {}
    max_files = _safe_int(args.get("max_files"))
    must_include = [str(item) for item in (args.get("must_include") or [])]
    repo = _repo_for_check(check, sandbox)
    started = time.monotonic()
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "diff", "--name-only", "HEAD~1", "HEAD"],
            cwd=str(sandbox),
            capture_output=True,
            text=True,
            timeout=timeout_s,
            check=False,
        )
        duration = time.monotonic() - started
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout.decode("utf-8", errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return "fail", {
            "command": ["git", "-C", str(repo), "diff", "--name-only", "HEAD~1", "HEAD"],
            "cwd": str(sandbox),
            "exit_code": 124,
            "duration_seconds": round(time.monotonic() - started, 3),
            "stdout_tail": _tail(stdout),
            "stderr_tail": _tail(stderr),
        }, ["timeout"]
    evidence = {
        "command": ["git", "-C", str(repo), "diff", "--name-only", "HEAD~1", "HEAD"],
        "cwd": str(sandbox),
        "exit_code": proc.returncode,
        "duration_seconds": round(duration, 3),
        "stdout_tail": _tail(proc.stdout),
        "stderr_tail": _tail(proc.stderr),
    }
    notes: list[str] = []
    if proc.returncode != 0:
        notes.append("not_a_git_repo")
        return "fail", evidence, notes
    files = [line.strip() for line in proc.stdout.splitlines() if line.strip()]
    ok_len = True if max_files is None else len(files) <= max_files
    ok_include = all(item in files for item in must_include)
    verdict = "pass" if ok_len and ok_include else "fail"
    evidence.update({"files": files, "max_files": max_files, "must_include": must_include})
    return verdict, evidence, notes


def _check_git_grep_count(check: dict[str, Any], sandbox: Path, timeout_s: float) -> tuple[str, dict[str, Any], list[str]]:
    args = check.get("args") if isinstance(check.get("args"), dict) else {}
    pattern = str(args.get("pattern") or check.get("pattern") or "")
    if not pattern:
        return "unknown_check", {}, ["git_grep_count_missing_pattern"]
    min_count = _safe_int(args.get("min"))
    max_count = _safe_int(args.get("max"))
    repo = _repo_for_check(check, sandbox)
    started = time.monotonic()
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "grep", "-c", "--", pattern],
            cwd=str(sandbox),
            capture_output=True,
            text=True,
            timeout=timeout_s,
            check=False,
        )
        duration = time.monotonic() - started
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout.decode("utf-8", errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return "fail", {
            "pattern": pattern,
            "exit_code": 124,
            "duration_seconds": round(time.monotonic() - started, 3),
            "stdout_tail": _tail(stdout),
            "stderr_tail": _tail(stderr),
        }, ["timeout"]
    total = 0
    for line in proc.stdout.splitlines():
        try:
            total += int(line.rsplit(":", 1)[1])
        except (IndexError, ValueError):
            continue
    if proc.returncode not in (0, 1):
        return "fail", {
            "pattern": pattern,
            "exit_code": proc.returncode,
            "duration_seconds": round(duration, 3),
            "stdout_tail": _tail(proc.stdout),
            "stderr_tail": _tail(proc.stderr),
        }, []
    ok_min = True if min_count is None else total >= min_count
    ok_max = True if max_count is None else total <= max_count
    return ("pass" if ok_min and ok_max else "fail"), {
        "pattern": pattern,
        "count": total,
        "min": min_count,
        "max": max_count,
        "exit_code": proc.returncode,
        "duration_seconds": round(duration, 3),
        "stdout_tail": _tail(proc.stdout),
        "stderr_tail": _tail(proc.stderr),
    }, []


def _score_one_success_check(check: dict[str, Any], sandbox: Path, timeout_s: float) -> tuple[str, dict[str, Any], list[str]]:
    check_type = check.get("type")
    if check_type == "pytest_passes":
        return _check_pytest_passes(check, sandbox, timeout_s)
    if check_type == "mcp_tool_listed":
        return _check_mcp_tool_listed(check)
    if check_type == "files_modified":
        return _check_files_modified(check, sandbox, timeout_s)
    if check_type == "git_grep_count":
        return _check_git_grep_count(check, sandbox, timeout_s)
    if check_type == "paraphrase_check":
        return "deferred", {}, ["paraphrase_unimplemented"]
    if check_type == "manual":
        return "manual_pending", {}, ["requires_human_review"]
    return "unknown_check", {}, [f"unknown_check_type:{check_type}"]


def _combine_verdicts(verdicts: Sequence[str]) -> str:
    if not verdicts:
        return "unknown_check"
    if any(v == "unknown_check" for v in verdicts):
        return "unknown_check"
    if any(v == "fail" for v in verdicts):
        return "fail"
    if any(v == "manual_pending" for v in verdicts):
        return "manual_pending"
    if any(v == "deferred" for v in verdicts):
        return "deferred"
    if all(v == "pass" for v in verdicts):
        return "pass"
    return verdicts[0]


def score_manifest_task(task: dict[str, Any], *, sandbox: Path, all_events: dict[str, list[VisibilityEvent]], timeout_s: float) -> dict[str, Any]:
    task_id = str(task.get("task_id") or task.get("taskId") or "")
    workload_id = task.get("workload_id") or task.get("workloadId")
    success_check = task.get("success_check")
    checks = success_check if isinstance(success_check, list) else [success_check]
    check_results: list[dict[str, Any]] = []
    verdicts: list[str] = []
    notes: list[str] = []
    evidence: dict[str, Any]
    for check in checks:
        if not isinstance(check, dict):
            verdict, check_evidence, check_notes = "unknown_check", {}, ["success_check_missing_or_invalid"]
            check_type = None
        else:
            verdict, check_evidence, check_notes = _score_one_success_check(check, sandbox, timeout_s)
            check_type = check.get("type")
        verdicts.append(verdict)
        notes.extend(check_notes)
        check_results.append({"type": check_type, "verdict": verdict, "evidence": check_evidence, "notes": check_notes})
    final_verdict = _combine_verdicts(verdicts)
    if len(check_results) == 1:
        evidence = check_results[0]["evidence"]
    else:
        evidence = {"checks": check_results}

    task_m7 = _task_m7_count(task_id, all_events) if task_id else 0
    if str(workload_id).upper() == "W7" and task_m7 == 0:
        notes.append("m7_zero_in_collab_workload")
    metrics = {"M7_capability_manifest_calls": task_m7}
    if task_m7:
        evidence = dict(evidence)
        evidence["M7_capability_manifest_calls"] = task_m7

    return {
        "schema_version": 1,
        "task_id": task_id,
        "workload_id": workload_id,
        "owner_expected": task.get("owner_expected") or task.get("ownerExpected"),
        "owner_actual": (_owner_actual(task_id, all_events) if task_id else None) or task.get("owner_expected") or task.get("ownerExpected"),
        "verdict": final_verdict,
        "success_check": success_check,
        "evidence": evidence,
        "metrics": metrics,
        "notes": notes,
    }


# ---------------------------------------------------------------------------
# Agent / M12 scoring


def _agent_backend(agent: str, events: Sequence[VisibilityEvent]) -> str | None:
    counts = Counter(event.backend for event in events if event.backend)
    return counts.most_common(1)[0][0] if counts else None


def _infer_backend_from_agent_name(agent: str) -> str | None:
    if agent.startswith("codex-"):
        return "codex_app_server"
    if agent.startswith("gemini-"):
        return "gemini_headless"
    if agent.startswith("kimi-"):
        return "kimi_headless"
    if agent.startswith("claude-"):
        return "claude_native"
    return None


def _partial_events_only(events: Sequence[VisibilityEvent]) -> bool:
    return any(event.kind in TERMINAL_KINDS and event.payload.get("partial_events_available") is False for event in events)


def _flatten_violations(events: Sequence[VisibilityEvent], backend: str | None) -> list[dict[str, Any]]:
    violations: list[dict[str, Any]] = []
    if backend is None:
        return violations
    for event in events:
        if event.kind != "tool_event":
            continue
        payload = event.payload or {}
        category = payload.get("category")
        tool_name = payload.get("tool_name")
        raw_tool_name = str(tool_name) if tool_name is not None else None
        # Gemini ACP legitimately has native events named "tool_call".  For
        # Codex-native host tools, generic names indicate a §1 flattener leak.
        if backend in {"codex_app_server", "codex_exec"} and category == "host_tool":
            whitelist = RAW_TOOL_NAME_WHITELIST.get(backend, set())
            if raw_tool_name not in whitelist:
                violations.append(
                    {
                        "event_id": event.event_id,
                        "raw_tool_name": raw_tool_name,
                        "backend": backend,
                        "kind": event.kind,
                    }
                )
    return violations


def score_agent(agent: str, events: Sequence[VisibilityEvent], *, scenario: str, run_id: str) -> dict[str, Any]:
    backend = _agent_backend(agent, events) or _infer_backend_from_agent_name(agent)
    observed = sorted({event.kind for event in events})
    notes: list[str] = []
    if not events:
        notes.append("empty_log")
    if backend is None:
        notes.append("unknown_backend:empty_log")
        expected: list[str] = []
        coverage_ratio = 0.0
        missing: list[str] = []
    elif backend not in EXPECTED_KINDS_PER_BACKEND:
        notes.append(f"unknown_backend:{backend}")
        expected = []
        coverage_ratio = None
        missing = []
    else:
        expected = list(EXPECTED_KINDS_PER_BACKEND[backend])
        missing = sorted(set(expected) - set(observed))
        partial_only = _partial_events_only(events)
        if partial_only:
            missing = [kind for kind in missing if kind not in {"tool_event", "artifact_event", "turn_progress"}]
        coverage_ratio = (len(expected) - len(missing)) / len(expected) if expected else None
    partial_only = _partial_events_only(events)

    visibility_degraded = [event for event in events if event.kind == "visibility_degraded"]
    surface_counts = {surface: 0 for surface in DEFAULT_SURFACES}
    for event in visibility_degraded:
        surface = str(event.payload.get("surface") or "_unknown_surface")
        surface_counts[surface] = surface_counts.get(surface, 0) + 1
    capability_calls = [event for event in events if event.kind == "tool_event" and _tool_name(event) == "mcp_anyteam_capability_manifest"]
    generic_tool_call_count = sum(1 for event in events if event.kind == "tool_event" and _tool_name(event) == "tool_call")
    rounded_coverage = round(coverage_ratio, 3) if isinstance(coverage_ratio, (int, float)) else coverage_ratio

    return {
        "schema_version": 1,
        "agent": agent,
        "backend": backend,
        "scenario": scenario,
        "run_id": run_id,
        "metrics": {
            "M6_visibility_degraded_count": len(visibility_degraded),
            "M6_by_surface": surface_counts,
            "M7_capability_manifest_calls": len(capability_calls),
            "M12_envelope_shape_coverage": {
                "expected_kinds_per_backend": expected,
                "observed_kinds": observed,
                "missing_kinds": missing,
                "coverage_ratio": rounded_coverage,
                "partial_events_only": partial_only,
            },
            "s1_generic_tool_call_count": generic_tool_call_count,
        },
        "s1_flatten_violations": _flatten_violations(events, backend),
        "notes": notes,
    }


def score_agent_events(agent: str, events: Sequence[VisibilityEvent], *, scenario: str, run_id: str) -> dict[str, Any]:
    """Compatibility wrapper used by the brief's unit tests."""

    return score_agent(agent, events, scenario=scenario, run_id=run_id)


def score_task(
    task: dict[str, Any],
    *,
    sandbox: Path,
    owner_actual: str | None = None,
    task_m7: int = 0,
    pytest_timeout_s: float = 600.0,
) -> dict[str, Any]:
    """Score one manifest task without requiring an event-log fixture.

    The production path is ``score_manifest_task``; this helper keeps the
    workload-check runners directly testable.
    """

    events: dict[str, list[VisibilityEvent]] = {}
    if task.get("task_id") and (owner_actual or task_m7):
        # ``score_manifest_task`` derives owner/M7 from events in production.
        # For unit tests, apply explicit overrides after the check result.
        events = {}
    result = score_manifest_task(task, sandbox=sandbox, all_events=events, timeout_s=pytest_timeout_s)
    if owner_actual is not None:
        result["owner_actual"] = owner_actual
    elif result.get("owner_actual") is None:
        result["owner_actual"] = task.get("owner_expected") or task.get("ownerExpected")
    result.setdefault("metrics", {})["M7_capability_manifest_calls"] = task_m7
    if task_m7:
        result["evidence"] = dict(result.get("evidence") or {})
        result["evidence"]["M7_capability_manifest_calls"] = task_m7
    if str(task.get("workload_id") or task.get("workloadId")).upper() == "W7" and task_m7 == 0:
        result.setdefault("notes", [])
        if "m7_zero_in_collab_workload" not in result["notes"]:
            result["notes"].append("m7_zero_in_collab_workload")
    return result


# ---------------------------------------------------------------------------
# Scenario aggregation / writing


def aggregate_scenario(
    *,
    scenario: str,
    run_id: str,
    task_scores: Sequence[dict[str, Any]],
    agent_scores: Sequence[dict[str, Any]],
    per_task_files: Sequence[str],
    per_agent_files: Sequence[str],
    input_warnings: Sequence[str],
) -> dict[str, Any]:
    verdict_counter = Counter(str(score.get("verdict")) for score in task_scores)
    task_verdicts = {key: verdict_counter.get(key, 0) for key in ("pass", "fail", "deferred", "manual_pending", "unknown_check")}
    total_tasks = sum(task_verdicts.values())
    task_pass_rate = round(task_verdicts["pass"] / total_tasks, 3) if total_tasks else None
    ratios: list[float] = []
    backends_below: set[str] = set()
    m6 = 0
    m7 = 0
    for score in agent_scores:
        metrics = score["metrics"]
        m6 += int(metrics.get("M6_visibility_degraded_count") or 0)
        m7 += int(metrics.get("M7_capability_manifest_calls") or 0)
        ratio = metrics["M12_envelope_shape_coverage"].get("coverage_ratio")
        if isinstance(ratio, (int, float)):
            ratios.append(float(ratio))
            if ratio < 0.5 and score.get("backend"):
                backends_below.add(str(score["backend"]))
    average_ratio = round(sum(ratios) / len(ratios), 3) if ratios else None
    return {
        "schema_version": 1,
        "scenario": scenario,
        "run_id": run_id,
        "task_verdicts": task_verdicts,
        "task_pass_rate": task_pass_rate,
        "M6_team_total_visibility_degraded": m6,
        "M7_team_total_capability_manifest_calls": m7,
        "M12_team_average_coverage_ratio": average_ratio,
        "M12_backends_below_threshold": sorted(backends_below),
        "per_task_files": list(per_task_files),
        "per_agent_files": list(per_agent_files),
        "input_warnings": list(input_warnings),
    }


def run_score(
    *,
    team: str | None,
    events_dir: Path | None,
    sandbox: Path,
    workload_manifest: Path,
    scenario: str,
    run_id: str,
    out: Path,
    check_timeout_s: float,
) -> dict[str, Any]:
    if not sandbox.exists() or not sandbox.is_dir():
        raise FileNotFoundError(f"sandbox path does not exist: {sandbox}")
    manifest = load_workload_manifest(workload_manifest)
    all_events, warnings = load_events(team=team, events_dir=events_dir)

    task_scores = [
        score_manifest_task(task, sandbox=sandbox, all_events=all_events, timeout_s=check_timeout_s)
        for task in manifest["tasks"]
        if isinstance(task, dict)
    ]
    if len(task_scores) != len(manifest["tasks"]):
        warnings.append("non_object_task_entries_skipped")

    agent_scores = [
        score_agent(agent, events, scenario=scenario, run_id=run_id)
        for agent, events in sorted(all_events.items())
    ]

    per_task_files: list[str] = []
    for score in task_scores:
        rel = Path("tasks") / f"{score['task_id'] or 'unknown'}.json"
        _write_json(out / rel, score)
        per_task_files.append(rel.as_posix())

    per_agent_files: list[str] = []
    for score in agent_scores:
        rel = Path("agents") / f"{score['agent']}.json"
        _write_json(out / rel, score)
        per_agent_files.append(rel.as_posix())

    scenario_score = aggregate_scenario(
        scenario=scenario,
        run_id=run_id,
        task_scores=task_scores,
        agent_scores=agent_scores,
        per_task_files=per_task_files,
        per_agent_files=per_agent_files,
        input_warnings=warnings,
    )
    _write_json(out / "scenario.json", scenario_score)
    return scenario_score


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Score Phase 3 workload correctness and M12 envelope shape coverage.")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--team", help="Team name; resolves ~/.claude/teams/<team>/events/*.jsonl")
    source.add_argument("--events-dir", type=Path, help="Explicit archived events directory")
    parser.add_argument("--sandbox", type=Path, required=True, help="Workload sandbox root")
    parser.add_argument("--workload-manifest", type=Path, required=True, help="JSON workload manifest from run_scenario.py")
    parser.add_argument("--scenario", required=True, help="Scenario id, e.g. S5")
    parser.add_argument("--run-id", required=True, help="Run id/timestamp")
    parser.add_argument("--out", type=Path, required=True, help="Output directory for JSON scorecards")
    parser.add_argument("--check-timeout-s", type=float, default=600.0, help=argparse.SUPPRESS)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        scenario_score = run_score(
            team=args.team,
            events_dir=args.events_dir,
            sandbox=args.sandbox,
            workload_manifest=args.workload_manifest,
            scenario=args.scenario,
            run_id=args.run_id,
            out=args.out,
            check_timeout_s=args.check_timeout_s,
        )
    except ManifestError as exc:
        _warn(str(exc))
        return 3
    except FileNotFoundError as exc:
        _warn(str(exc))
        return 1
    except OSError as exc:
        _warn(f"output write failed: {exc}")
        return 2

    print(
        "score_quality: "
        f"task_verdicts={scenario_score['task_verdicts']} "
        f"M12_avg={scenario_score['M12_team_average_coverage_ratio']}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
