"""Environment variable names and helpers for claude-anyteam.

The public, documented names use the `CLAUDE_ANYTEAM_*` prefix. We still
honor the older `CODEX_TEAMMATE_*` names as fallbacks where practical so
existing local installs keep working during the rebrand.
"""

from __future__ import annotations

from collections.abc import Mapping

TEAM_ENV = "CLAUDE_ANYTEAM_TEAM"
LEGACY_TEAM_ENV = "CODEX_TEAMMATE_TEAM"

NAME_ENV = "CLAUDE_ANYTEAM_NAME"
LEGACY_NAME_ENV = "CODEX_TEAMMATE_NAME"

CWD_ENV = "CLAUDE_ANYTEAM_CWD"
LEGACY_CWD_ENV = "CODEX_TEAMMATE_CWD"

POLL_ENV = "CLAUDE_ANYTEAM_POLL_S"
LEGACY_POLL_ENV = "CODEX_TEAMMATE_POLL_S"

COLOR_ENV = "CLAUDE_ANYTEAM_COLOR"
LEGACY_COLOR_ENV = "CODEX_TEAMMATE_COLOR"

PLAN_MODE_ENV = "CLAUDE_ANYTEAM_PLAN_MODE"
LEGACY_PLAN_MODE_ENV = "CODEX_TEAMMATE_PLAN_MODE"

APP_SERVER_ENV = "CLAUDE_ANYTEAM_APP_SERVER"
LEGACY_APP_SERVER_ENV = "CODEX_TEAMMATE_APP_SERVER"

MODEL_ENV = "CLAUDE_ANYTEAM_MODEL"
LEGACY_MODEL_ENV = "CODEX_TEAMMATE_MODEL"

EFFORT_ENV = "CLAUDE_ANYTEAM_EFFORT"
LEGACY_EFFORT_ENV = "CODEX_TEAMMATE_EFFORT"

LOG_ENV = "CLAUDE_ANYTEAM_LOG"
LEGACY_LOG_ENV = "CODEX_TEAMMATE_LOG"

BINARY_ENV = "CLAUDE_ANYTEAM_BINARY"
LEGACY_BINARY_ENV = "CODEX_TEAMMATE_BINARY"
GEMINI_BINARY_ENV = "CLAUDE_ANYTEAM_GEMINI_BINARY"
KIMI_BINARY_ENV = "CLAUDE_ANYTEAM_KIMI_BINARY"

SHIM_MATCH_ENV = "CLAUDE_ANYTEAM_SHIM_MATCH"
LEGACY_SHIM_MATCH_ENV = "CODEX_TEAMMATE_SHIM_MATCH"
GEMINI_SHIM_MATCH_ENV = "CLAUDE_ANYTEAM_GEMINI_SHIM_MATCH"
KIMI_SHIM_MATCH_ENV = "CLAUDE_ANYTEAM_KIMI_SHIM_MATCH"

NATIVE_CLAUDE_ENV = "CLAUDE_ANYTEAM_NATIVE_CLAUDE"
LEGACY_NATIVE_CLAUDE_ENV = "CODEX_TEAMMATE_NATIVE_CLAUDE"

DUMP_EVENTS_ENV = "CLAUDE_ANYTEAM_DUMP_EVENTS"
LEGACY_DUMP_EVENTS_ENV = "CODEX_TEAMMATE_DUMP_EVENTS"

PROBE_TAG_ENV = "CLAUDE_ANYTEAM_PROBE_TAG"
LEGACY_PROBE_TAG_ENV = "CODEX_TEAMMATE_PROBE_TAG"

PYTHON_PACKAGE_ENV = "CLAUDE_ANYTEAM_PYTHON_PACKAGE"
LEGACY_PYTHON_PACKAGE_ENV = "CODEX_TEAMMATE_PYTHON_PACKAGE"

UV_INSTALL_DIR_ENV = "CLAUDE_ANYTEAM_UV_INSTALL_DIR"
LEGACY_UV_INSTALL_DIR_ENV = "CODEX_TEAMMATE_UV_INSTALL_DIR"

UV_TOOL_BIN_DIR_ENV = "CLAUDE_ANYTEAM_UV_TOOL_BIN_DIR"
LEGACY_UV_TOOL_BIN_DIR_ENV = "CODEX_TEAMMATE_UV_TOOL_BIN_DIR"


def env_first(env: Mapping[str, str], *names: str, default: str | None = None) -> str | None:
    for name in names:
        value = env.get(name)
        if value not in (None, ""):
            return value
    return default


def identity_env(env: Mapping[str, str], *, team: str, name: str) -> dict[str, str]:
    merged = dict(env)
    merged[TEAM_ENV] = team
    merged[NAME_ENV] = name
    merged[LEGACY_TEAM_ENV] = team
    merged[LEGACY_NAME_ENV] = name
    return merged
