"""Environment variable names and helpers for claude-anyteam.

The public, documented names use the `CLAUDE_ANYTEAM_*` prefix. We still
honor the older `CODEX_TEAMMATE_*` names as fallbacks where practical so
existing local installs keep working during the rebrand.
"""

from __future__ import annotations

from collections.abc import Mapping

TEAM_ENV = "CLAUDE_ANYTEAM_TEAM"
LEGACY_TEAM_ENV = "CODEX_TEAMMATE_TEAM"

NAME_ENV = "CLAUDE_ANYTEAM_NAME"
LEGACY_NAME_ENV = "CODEX_TEAMMATE_NAME"

CWD_ENV = "CLAUDE_ANYTEAM_CWD"
LEGACY_CWD_ENV = "CODEX_TEAMMATE_CWD"

POLL_ENV = "CLAUDE_ANYTEAM_POLL_S"
LEGACY_POLL_ENV = "CODEX_TEAMMATE_POLL_S"

COLOR_ENV = "CLAUDE_ANYTEAM_COLOR"
LEGACY_COLOR_ENV = "CODEX_TEAMMATE_COLOR"

PLAN_MODE_ENV = "CLAUDE_ANYTEAM_PLAN_MODE"
LEGACY_PLAN_MODE_ENV = "CODEX_TEAMMATE_PLAN_MODE"

APP_SERVER_ENV = "CLAUDE_ANYTEAM_APP_SERVER"
LEGACY_APP_SERVER_ENV = "CODEX_TEAMMATE_APP_SERVER"

MODEL_ENV = "CLAUDE_ANYTEAM_MODEL"
LEGACY_MODEL_ENV = "CODEX_TEAMMATE_MODEL"

EFFORT_ENV = "CLAUDE_ANYTEAM_EFFORT"
LEGACY_EFFORT_ENV = "CODEX_TEAMMATE_EFFORT"

TURN_TIMEOUT_ENV = "CLAUDE_ANYTEAM_TURN_TIMEOUT_S"
LEGACY_TURN_TIMEOUT_ENV = "CODEX_TEAMMATE_TURN_TIMEOUT_S"

NON_PROGRESS_WARN_ENV = "CLAUDE_ANYTEAM_NON_PROGRESS_WARN_S"
LEGACY_NON_PROGRESS_WARN_ENV = "CODEX_TEAMMATE_NON_PROGRESS_WARN_S"

NON_PROGRESS_INTERRUPT_ENV = "CLAUDE_ANYTEAM_NON_PROGRESS_INTERRUPT_S"
LEGACY_NON_PROGRESS_INTERRUPT_ENV = "CODEX_TEAMMATE_NON_PROGRESS_INTERRUPT_S"

WRAPPER_TOOL_FAILURE_WINDOW_ENV = "CLAUDE_ANYTEAM_WRAPPER_TOOL_FAILURE_WINDOW_S"

# Codex CLI sqlite WAL-bloat mitigation (#43). These are claude-anyteam-owned
# controls for warning on large ``logs_*.sqlite-wal`` files and attempting a
# bounded sqlite checkpoint before spawning Codex App Server.
CODEX_WAL_WARN_THRESHOLD_BYTES_ENV = (
    "CLAUDE_ANYTEAM_CODEX_SQLITE_WAL_WARN_THRESHOLD_BYTES"
)
CODEX_WAL_CHECKPOINT_ENV = "CLAUDE_ANYTEAM_CODEX_SQLITE_WAL_CHECKPOINT"
CODEX_WAL_CHECKPOINT_TIMEOUT_ENV = (
    "CLAUDE_ANYTEAM_CODEX_SQLITE_WAL_CHECKPOINT_TIMEOUT_S"
)

TEAM_KILL_GRACEFUL_TIMEOUT_ENV = "CLAUDE_ANYTEAM_TEAM_KILL_GRACEFUL_TIMEOUT_S"

# Codex App Server JSON-RPC ``initialize`` budget (#40 Phase 1).
# Default 90s — chosen because the only successful empirical sample we
# have (codex-reviewer turn 1, parking-ack prompt, ~17s) is well under
# 90s. Override via env when a legitimate first-cold-start on a complex
# prompt needs longer; the new ``app_server_initialize_completed`` event
# records ``elapsed_ms`` and ``prompt_byte_size`` per success so we can
# revisit the default with data, not vibes.
APP_SERVER_INITIALIZE_TIMEOUT_ENV = "CLAUDE_ANYTEAM_APP_SERVER_INITIALIZE_TIMEOUT_S"
# Cadence (in seconds) for ``app_server_initialize_progress`` typed
# events emitted while waiting on JSON-RPC ``initialize`` (#40 Phase 1).
# Default 30s. Set to 0 to disable progress emission entirely.
APP_SERVER_INITIALIZE_PROGRESS_INTERVAL_ENV = (
    "CLAUDE_ANYTEAM_APP_SERVER_INITIALIZE_PROGRESS_INTERVAL_S"
)

LOG_ENV = "CLAUDE_ANYTEAM_LOG"
LEGACY_LOG_ENV = "CODEX_TEAMMATE_LOG"

BINARY_ENV = "CLAUDE_ANYTEAM_BINARY"
LEGACY_BINARY_ENV = "CODEX_TEAMMATE_BINARY"
GEMINI_BINARY_ENV = "CLAUDE_ANYTEAM_GEMINI_BINARY"
KIMI_BINARY_ENV = "CLAUDE_ANYTEAM_KIMI_BINARY"

SHIM_MATCH_ENV = "CLAUDE_ANYTEAM_SHIM_MATCH"
LEGACY_SHIM_MATCH_ENV = "CODEX_TEAMMATE_SHIM_MATCH"
CLAUDE_SHIM_MATCH_ENV = "CLAUDE_ANYTEAM_CLAUDE_SHIM_MATCH"
GEMINI_SHIM_MATCH_ENV = "CLAUDE_ANYTEAM_GEMINI_SHIM_MATCH"
KIMI_SHIM_MATCH_ENV = "CLAUDE_ANYTEAM_KIMI_SHIM_MATCH"
ALLOW_BARE_PREFIX_ENV = "CLAUDE_ANYTEAM_ALLOW_BARE_PREFIX"

NATIVE_CLAUDE_ENV = "CLAUDE_ANYTEAM_NATIVE_CLAUDE"
LEGACY_NATIVE_CLAUDE_ENV = "CODEX_TEAMMATE_NATIVE_CLAUDE"

DUMP_EVENTS_ENV = "CLAUDE_ANYTEAM_DUMP_EVENTS"
LEGACY_DUMP_EVENTS_ENV = "CODEX_TEAMMATE_DUMP_EVENTS"

PROBE_TAG_ENV = "CLAUDE_ANYTEAM_PROBE_TAG"
LEGACY_PROBE_TAG_ENV = "CODEX_TEAMMATE_PROBE_TAG"

PYTHON_PACKAGE_ENV = "CLAUDE_ANYTEAM_PYTHON_PACKAGE"
LEGACY_PYTHON_PACKAGE_ENV = "CODEX_TEAMMATE_PYTHON_PACKAGE"

UV_INSTALL_DIR_ENV = "CLAUDE_ANYTEAM_UV_INSTALL_DIR"
LEGACY_UV_INSTALL_DIR_ENV = "CODEX_TEAMMATE_UV_INSTALL_DIR"

UV_TOOL_BIN_DIR_ENV = "CLAUDE_ANYTEAM_UV_TOOL_BIN_DIR"
LEGACY_UV_TOOL_BIN_DIR_ENV = "CODEX_TEAMMATE_UV_TOOL_BIN_DIR"


def env_first(env: Mapping[str, str], *names: str, default: str | None = None) -> str | None:
    for name in names:
        value = env.get(name)
        if value not in (None, ""):
            return value
    return default


def identity_env(env: Mapping[str, str], *, team: str, name: str) -> dict[str, str]:
    merged = dict(env)
    merged[TEAM_ENV] = team
    merged[NAME_ENV] = name
    merged[LEGACY_TEAM_ENV] = team
    merged[LEGACY_NAME_ENV] = name
    return merged
